'use client';
import { useEffect, useState } from 'react';
import { Button, Container, Input, TextArea, Checkbox, Row, Col } from '@nextui-org/react';
import Head from 'next/head';

import { useEditor, EditorContent } from '@tiptap/react'
import StarterKit from '@tiptap/starter-kit'

const Editor = (props) => {
  const [title, setTitle] = useState('');
  const [description, setDescription] = useState('');
  const [editorTools, setEditorTools] = useState();
  const [value, setValue] = useState("**Hello world!!!**");

  const editor = useEditor({
    extensions: [
      StarterKit,
    ],
    content: '<p>Hello World! 🌎️</p>',
  })

  const onSaveHandler = async (editorInstance) => {
    try {
      const blogData = await editorInstance.save();
      if (!title || title === '')
        throw new Error('Title cannot be empty. Please enter title');
      if (!blogData.blocks[0])
        throw new Error('Blog cannot be empty. Please enter some data');
      props.onSave(blogData, title, description);
    } catch (err) {
      console.log(err);
    }
  };

  const inputStyle = {
    maxWidth: '500px',
    marginBottom: '20px',
    height: '30px'
  };

  return (
    <div style={{ display: 'flex', flexDirection: 'column'}}>
      <Head>
        <title>Create Blog</title>
        <meta name='description' content='Generated by create next app' />
      </Head>
      <Container gap={0}>
        <Row gap={1}>
          <Col>
            <Input
              labelPlaceholder='Your Blog Title'
              value={title}
              onChange={(event) => setTitle(event.target.value)}
            />
          </Col>
          <Col>
            <div style={{display: 'flex'}}>
               
               <Button ghost color="secondary" onClick={() => {}}>Save</Button>
               <Button contained color="primary" disabled>Publish</Button>
            </div>
          </Col>
        </Row>
        <Row>
          <Col>
                <EditorContent editor={editor} />

              </Col>
        </Row>
      </Container>
    </div>
  );
};

export default Editor;
