import { Grid, Typography, Menu, MenuItem } from "@mui/material";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import styles from "../styles/Home.module.css";

const Articles: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>mike.dupree.ca | Articles</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        sx={{
          margin: "4rem 0 2rem",
          display:'flex',
          justifyContent:'center'
        }}
      >
        <Typography variant="h1" sx={{textAlign: 'center'}}>
          Articles
        </Typography>

      </Grid>

    </div>
  );
};

export default Articles;

export const getStaticProps: GetStaticProps = async (context) => {
  console.log("context", context);
  return { props: {} };
};
