import { Grid, Typography } from "@mui/material";
import type { NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";

const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>mike.dupree.ca | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        sx={{
          margin: "4rem 0 2rem",
        }}
      >
        <Grid item xs={6} md={8}>
          <Grid item xs={12} md={12} sx={{ height: "100%" }}>
            <Grid
              container
              sx={{ height: "100%", display: "flex", alignItems: "center" }}
            >
              <Grid item xs={6} md={8}>
                <Typography
                  variant="h3"
                  color="primary"
                  sx={{ textAlign: "center" }}
                >
                  MIKE DUPREE
                </Typography>
                <Typography
                  variant="h4"
                  color="secondary"
                  sx={{ textAlign: "center" }}
                >
                  Software Developer
                </Typography>
                <Typography
                  variant="h4"
                  color="secondary"
                  sx={{ textAlign: "center" }}
                >
                  Team Lead
                </Typography>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
        <Grid item xs={6} md={4}>
          <Image
            src={"/Images/MikeDupree.jpeg"}
            width="500"
            height="500"
            alt="Personal Picture"
            style={{ borderRadius: "50%" }}
          />
        </Grid>
      </Grid>
    </div>
  );
};

export default Home;
