import { Grid, Typography, Menu, MenuItem } from "@mui/material";
import type { GetStaticProps, NextPage } from "next";
import Head from "next/head";
import Image from "next/image";
import styles from "../styles/Home.module.css";
import axios from "axios";
const Home: NextPage = () => {
  return (
    <div className={styles.container}>
      <Head>
        <title>mike.dupree.ca | Home</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <Grid
        container
        sx={{
          margin: "4rem 0 2rem",
        }}
      >
        <Grid item xs={6} md={8}>
          <Grid item xs={12} md={12} sx={{ height: "100%" }}>
            <Grid
              container
              sx={{ height: "100%", display: "flex", alignItems: "center" }}
            >
              <Grid item xs={6} md={8}>
                <Typography
                  variant="h3"
                  color="primary"
                  sx={{ textAlign: "center" }}
                >
                  MIKE DUPREE
                </Typography>
                <Typography
                  variant="h4"
                  color="secondary"
                  sx={{ textAlign: "center" }}
                >
                  Software Developer
                </Typography>
                <Typography
                  variant="h4"
                  color="secondary"
                  sx={{ textAlign: "center" }}
                >
                  Team Lead
                </Typography>
              </Grid>
            </Grid>
          </Grid>
        </Grid>
        <Grid item xs={6} md={4}>
          <Image
            src={"/Images/MikeDupree.jpeg"}
            width="500"
            height="500"
            alt="Personal Picture"
            style={{ borderRadius: "50%" }}
          />
        </Grid>
      </Grid>

      <Grid
        container
        sx={{
          margin: "4rem 0 2rem",
          display: "flex",
          justifyContent: "center",
        }}
      >
        <Typography variant="h4" sx={{ textAlign: "center" }}>
          &quot;I like Rust, and maybe 3 people.&quot;
        </Typography>
      </Grid>
    </div>
  );
};

export default Home;

export const getStaticProps: GetStaticProps = async (context) => {
  console.log("context", context);
  const activitiyResponse = await axios
    .get(`https://gitlab.com/api/v4/projects/39317118/repository/commits`, {
      headers: {
        "PRIVATE-TOKEN": process.env.GITLAB_TOKEN,
      },
    })
    .catch((err) => console.log);

  const emails = ["mikerdupree@gmail.com", "cryptoasis.mail@gmail.com"];
  const cleanData = activitiyResponse?.data?.filter((r) =>
    emails.includes(r.author_email)
  );
  console.log("res data", activitiyResponse?.data);
  return { props: {} };
};
